# Generated by Django 2.2.3 on 2019-11-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis_0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_0', models.CharField(max_length=20, verbose_name='dxcode_0')),
                ('dxname_0', models.CharField(max_length=64, verbose_name='dxname_0')),
            ],
            options={
                'verbose_name': '진단세부0',
                'db_table': 'dx_0',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_1', models.CharField(max_length=20, verbose_name='dxcode_1')),
                ('dxname_1', models.CharField(max_length=64, verbose_name='dxname_1')),
                ('dxcode_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_0')),
            ],
            options={
                'verbose_name': '진단세부1',
                'db_table': 'dx_1',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_2', models.CharField(max_length=20, verbose_name='dxcode_2')),
                ('dxname_2', models.CharField(max_length=64, verbose_name='dxname_2')),
                ('dxcode_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_1')),
            ],
            options={
                'verbose_name': '진단세부2',
                'db_table': 'dx_2',
            },
        ),
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnumb', models.CharField(max_length=12, verbose_name='등록번호')),
                ('ptname', models.CharField(max_length=48, verbose_name='환자성명')),
                ('birthdate', models.DateField(verbose_name='생년월일')),
            ],
            options={
                'verbose_name': '환자기본정보',
                'db_table': 'pt_info',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='상품명')),
                ('price', models.IntegerField(verbose_name='상품가격')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '상품',
                'db_table': 'fascampus_product',
            },
        ),
        migrations.CreateModel(
            name='Pt_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dx_date', models.DateField(verbose_name='진단일')),
                ('dx_age', models.FloatField(verbose_name='연령')),
                ('dxcode_3', models.CharField(blank=True, max_length=40, verbose_name='Comment')),
                ('need_confirm', models.BooleanField(verbose_name='컨펌필요여부')),
                ('compl_confirm', models.BooleanField(verbose_name='컨펌완료여부')),
                ('dr_name', models.CharField(blank=True, max_length=40, verbose_name='주치의')),
                ('regist_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('dxcode_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_0', verbose_name='진단대분류')),
                ('dxcode_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_1', verbose_name='진단중분류')),
                ('dxcode_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_2', verbose_name='진단소분류')),
                ('regist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.Fcuser', verbose_name='작성자')),
                ('unitnumb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Patient_info', verbose_name='등록번호')),
            ],
            options={
                'verbose_name': '환자진단기록',
                'db_table': 'pt_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_3', models.CharField(max_length=20, verbose_name='dxcode_3')),
                ('dxname_3', models.CharField(max_length=64, verbose_name='dxname_3')),
                ('dxcode_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_2')),
            ],
            options={
                'verbose_name': '진단세부3',
                'db_table': 'dx_3',
            },
        ),
    ]
