# Generated by Django 2.2.3 on 2019-11-29 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='unitnumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Patient_info', verbose_name='환자등록번호'),
        ),
    ]
