# Generated by Django 2.2.3 on 2019-07-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20190720_2215'),
        ('product', '0002_auto_20190720_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis_0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_0', models.CharField(max_length=20, verbose_name='dxcode_0')),
                ('dxname_0', models.CharField(max_length=64, verbose_name='dxname_0')),
            ],
            options={
                'verbose_name': '진단세부0',
                'db_table': 'dx_0',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_1', models.CharField(max_length=20, verbose_name='dxcode_1')),
                ('dxname_1', models.CharField(max_length=64, verbose_name='dxname_1')),
                ('dxcode_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_0')),
            ],
            options={
                'verbose_name': '진단세부1',
                'db_table': 'dx_1',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_2', models.CharField(max_length=20, verbose_name='dxcode_2')),
                ('dxname_2', models.CharField(max_length=64, verbose_name='dxname_2')),
                ('dxcode_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_1')),
            ],
            options={
                'verbose_name': '진단세부2',
                'db_table': 'dx_2',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dxcode_3', models.CharField(max_length=20, verbose_name='dxcode_3')),
                ('dxname_3', models.CharField(max_length=64, verbose_name='dxname_3')),
                ('dxcode_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_2')),
            ],
            options={
                'verbose_name': '진단세부3',
                'db_table': 'dx_3',
            },
        ),
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnumb', models.CharField(max_length=12, verbose_name='등록번호')),
                ('ptname', models.CharField(max_length=48, verbose_name='환자성명')),
                ('birthdate', models.DateField(verbose_name='생년월일')),
            ],
            options={
                'verbose_name': '환자기본정보',
                'db_table': 'pt_info',
            },
        ),
        migrations.CreateModel(
            name='Pt_diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnumb', models.CharField(max_length=12, verbose_name='등록번호')),
                ('regist_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('dxcode_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_0', verbose_name='dxcode_0')),
                ('dxcode_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_1', verbose_name='dxcode_1')),
                ('dxcode_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_2', verbose_name='dxcode_2')),
                ('dxcode_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_3', verbose_name='dxcode_3')),
                ('regist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.Fcuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '환자진단기록',
                'db_table': 'pt_diagnosis',
            },
        ),
    ]
