# Generated by Django 2.2.3 on 2019-11-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191129_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='compl_confirm',
            field=models.BooleanField(default=False, verbose_name='컨펌완료여부'),
        ),
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='need_confirm',
            field=models.BooleanField(default=False, verbose_name='컨펌필요여부'),
        ),
    ]
