# Generated by Django 2.2.3 on 2019-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_diagnosis_0_diagnosis_1_diagnosis_2_diagnosis_3_patient_info_pt_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='dxcode_3',
            field=models.CharField(max_length=12, verbose_name='dxcode_3'),
        ),
    ]
