# Generated by Django 2.2.3 on 2019-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190721_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='dxcode_3',
            field=models.CharField(blank=True, max_length=12, verbose_name='dxcode_3'),
        ),
    ]
