# Generated by Django 2.2.3 on 2019-07-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190721_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='dxcode_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_0', verbose_name='진단대분류'),
        ),
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='dxcode_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_1', verbose_name='진단중분류'),
        ),
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='dxcode_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Diagnosis_2', verbose_name='진단소분류'),
        ),
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='dxcode_3',
            field=models.CharField(blank=True, max_length=12, verbose_name='진단상세'),
        ),
    ]
