# Generated by Django 2.2.3 on 2019-12-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191208_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='unitnumb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Patient_info', verbose_name='환자등록번호'),
        ),
    ]
