# Generated by Django 2.2.3 on 2020-02-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191208_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt_diagnosis',
            name='unitnumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Patient_info', unique=True, verbose_name='환자등록번호'),
        ),
    ]
