# Generated by Django 2.2.3 on 2020-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200215_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='unitnumb',
            field=models.IntegerField(max_length=12, unique=True, verbose_name='등록번호'),
        ),
    ]
