# Generated by Django 2.2.3 on 2020-02-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200216_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='unitnumb',
            field=models.IntegerField(unique=True, verbose_name='등록번호'),
        ),
    ]
