# Generated by Django 2.2.3 on 2019-11-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_physician'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='comment',
            field=models.CharField(default=11, max_length=15),
            preserve_default=False,
        ),
    ]
