# Generated by Django 2.2.3 on 2019-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_physician_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='comment',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
